### PR TITLE
Various Carousel and Header improvements

### PR DESCRIPTION
**Pull request by trieloff**
- fix(header): reduce mobile size (#35)
- fix(carousel): do not hide buttons on mobile (#7)
- feat(carousel): better mobile layout, reposition text on desktop (#7, #26)

This is not yet optimal, but about as good as I can get it done

Test URLs:
- After: https://mobile-carousel--birdiesforthebrave--hlxsites.hlx.page/

### CODE REVIEW

**Comment by cziegeler** [comment]
@trieloff Looks very good now, the only thing is that now the three buttons (circles) in the gallery are not inside the grey text box anymore but on the bottom right corner and hardly visible over the image.

**Comment by trieloff** [comment]
f2e0f12b3effa0a6

**Comment by trieloff** [comment]
2c11d13c276b0315

**Comment by trieloff** [comment]
11669556585861c7

**Comment by trieloff** [comment]
716200fec99f885a

**Pull request merged**
