### PR TITLE
Fix #30

### LINKED ISSUE #30: Cards: reduce font size, label box (blue background) needs consistent height
Screen Shot 2022-10-12 at 09 47 50 copy
Screen Shot 2022-10-12 at 10 04 39

### PR DESCRIPTION
**Pull request by karlpauls**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #30 

Test URLs:
- Before: https://main--birdiesforthebrave--hlxsites.hlx.page/
- After: https://issue30--birdiesforthebrave--hlxsites.hlx.page/

### CODE REVIEW

**Comment by cziegeler** [comment]
This breaks the layout of the cards icons

**Comment by karlpauls** [comment]
Good catch @cziegeler - this should only apply to the ".cards overlay" body. One moment.

**Comment by karlpauls** [comment]
@cziegeler - PTAL again :-)

**Review by cziegeler — APPROVED** [review]
Looks good now

**Comment by trieloff** [comment]
If we reduced the font size one notch, we could probably reduce the height of the box a bit more to stay in line with the original design.

**Comment by karlpauls** [comment]
@trieloff, I experimented quite a bit with that kind of thinking and I think this is best option we have to keep it simple. It does seem to work in all views I could find.

If you really want the pixel by pixel copy it would need to be done differently (either by using javascript like they do or by reworking this to be based on some kind of flex box/flexrow concept). I'm not sure that is worth the effort but if you want to try we can keep this one open as a backup.

**Comment by trieloff** [comment]
ok.

**Review by trieloff — APPROVED** [review]

**Pull request merged**
